robotiq_3f_gripper:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125

  gripper_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - palm_finger_1_joint
      - finger_1_joint_1
      - finger_1_joint_2
      - finger_1_joint_3
      - palm_finger_2_joint
      - finger_2_joint_1
      - finger_2_joint_2
      - finger_2_joint_3
      - finger_middle_joint_1
      - finger_middle_joint_2
      - finger_middle_joint_3
